# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml
[mgr]
prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
	{ on = [ "<C-g>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "<Tab>" ], run = [ "select --state=none", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = [ "<Space>" ], run = [ "select --state=none", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = [ "y", "y" ],         run = "yank",                       desc = "Copy the selected files" },
	{ on = [ "d", "d" ],         run = "yank --cut",                 desc = "Cut the selected files" },
	{ on = [ "D" ],         run = "remove",                     desc = "Move the files to the trash" },
	{ on = [ "p", "p" ],         run = "paste",                      desc = "Paste the files" },
	{ on = [ "+" ],         run = "create",                     desc = "Create a file or directory (ends with / for directories)" },
	{ on = [ "f" ],         run = "create",                     desc = "Create a file or directory (ends with / for directories)" },
  { on = [ "R" ],         run = "rename --cursor=before_ext", desc = "Rename a file or directory" },
	{ on = [ "<A-p>" ],         run = "search fd",                  desc = "Search files by name using fd" },
	{ on = [ "F" ], run = "filter --smart", desc = "Filter the files" },
	{ on = [ "y", "p" ], run = "copy path",             desc = "Copy the absolute path" },
	{ on = [ "y", "d" ], run = "copy dirname",          desc = "Copy the path of the parent directory" },
	{ on = [ "y", "n" ], run = "copy filename",         desc = "Copy the name of the file" },

	# Goto
	{ on = [ "b", "h" ],       run = "cd ~",             desc = "Go to the home directory" },
	{ on = [ "b", "c" ],       run = "cd ~/.config",     desc = "Go to the config directory" },
	{ on = [ "b", "d" ],       run = "cd ~/dev",     desc = "Go to the dev directory" },
	{ on = [ "b", "w" ],       run = "cd ~/dev/work",     desc = "Go to the work directory" },
	{ on = [ "b", "D" ],       run = "cd ~/Downloads",   desc = "Go to the downloads directory" },
	{ on = [ "b", "l" ],       run = "cd ~/dev-local",   desc = "Go to the dev-local directory" },
	{ on = [ "b", "e" ],       run = "cd ~/.config/doom",   desc = "Go to the doom directory" },
	{ on = [ "b", "E" ],       run = "cd ~/.config/emacs",   desc = "Go to the emacs directory" },
	{ on = [ "b", "<Space>" ], run = "cd --interactive", desc = "Go to a directory interactively" },
]

[tasks]
prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
	{ on = [ "<C-g>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
]

[select]
prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
	{ on = [ "<C-g>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
]


[input]
prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
	{ on = [ "<C-g>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
]

[completion]
prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
	{ on = [ "<C-g>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
]

[help]
prepend_keymap = [
	{ on = [ "?" ], run = "help", desc = "Open help" },
	{ on = [ "<C-g>" ], run = "escape",             desc = "Exit visual mode, clear selected, or cancel search" },
]
