# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml
[mgr]
show_hidden    = true
sort_dir_first = true

[opener]
play = [
	{ run = 'open "$@"', orphan = true, for = "unix" },
]
