# Font configuration
font:
  normal:
    family: OperatorMono Nerd Font
    style: Regular
  bold:
    family: OperatorMono Nerd Font
    style: Medium
  italic:
    family: OperatorMono Nerd Font
    style: Italic
  bold_italic:
    family: OperatorMono Nerd Font
    style: Medium Italic
  size: 14
