font:
  normal:
    family: Monofur Nerd Font Mono
    style: Regular
  bold:
    family: Monofur Nerd Font Mono
    style: Bold
  italic:
    family: Monofur Nerd Font Mono
    style: Italic
  size: 16
  offset:
    x: 0
    y: 0
