font:
  normal:
    family: Ellograph CFNerd Font
    style: Regular
  bold:
    family: Ellograph CFNerd Font
    style: Bold
  italic:
    family: Ellograph CFNerd Font
    style: Italic
  bold_italic:
    family: Ellograph CFNerd Font
    style: Bold Italic
  size: 14
  offset:
    x: 0
    y: 0
