font:
  normal:
    family: Cartograph CFNerd Font
    style: Regular
  bold:
    family: Cartograph CFNerd Font
    style: Bold
  italic:
    family: Cartograph CFNerd Font
    style: Italic
  bold_italic:
    family: Cartograph CFNerd Font
    style: Bold Italic
  size: 12
  offset:
    x: 0
    y: 0
